services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - btg-network

#  postgres:
#    image: postgres:16-alpine
#    environment:
#      - POSTGRES_DB=btg-order-reporting
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=password
#    ports:
#      - "5433:5432"
#    networks:
#      - btg-network


networks:
  btg-network:
    driver: bridge